# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2021 Canonical Ltd.
# Author: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>
#                             <krzk@kernel.org>

name: Linux kernel dtschema
on: [push, pull_request, workflow_dispatch]

jobs:
  job_dt_binding_check:
    name: dt_binding_check
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Git checkout Linux sources
      uses: actions/checkout@v2
      with:
        repository: krzk/linux.git
        ref: track/next
        path: sources

    - name: Install additional packages
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends build-essential python3-pip libyaml-dev
        pip install dtschema yamllint

    - name: Make allyesconfig
      run: make allyesconfig
      working-directory: ./sources

    - name: Make dt_binding_check
      id: make_dt_binding_check
      run: |
        (make -j$(nproc) dt_binding_check | tee ../log-dt_binding_check-stdout.log) \
          3>&1 1>&2 2>&3 | tee ../log-dt_binding_check-stderr.log
      working-directory: ./sources

    - name: Look for warnings in dt_binding_check stdout
      run: |
        grep -C 1 -P '^[^\s]+:\s' log-dt_binding_check-stdout.log
      if: ${{ always() && ((steps.make_dt_binding_check.outcome == 'failure') ||
                           (steps.make_dt_binding_check.outcome == 'success')) }}

    - name: Print dt_binding_check stderr
      run: |
        cat log-dt_binding_check-stderr.log
      if: ${{ always() && ((steps.make_dt_binding_check.outcome == 'failure') ||
                           (steps.make_dt_binding_check.outcome == 'success')) }}

  job_dtbs_check:
    name: dtbs_check
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - config: allyesconfig
            env:
              ARCH: arm
              CROSS_COMPILE: arm-linux-gnueabi-
          - config: multi_v4t_defconfig
            env:
              ARCH: arm
              CROSS_COMPILE: arm-linux-gnueabi-
          - config: multi_v5_defconfig
            env:
              ARCH: arm
              CROSS_COMPILE: arm-linux-gnueabi-
          - config: allyesconfig
            env:
              ARCH: arm64
              CROSS_COMPILE: aarch64-linux-gnu-
          - config: allyesconfig
            env:
              ARCH: mips
              CROSS_COMPILE: mips-linux-gnu-
          - config: allyesconfig
            env:
              ARCH: powerpc
              CROSS_COMPILE: powerpc-linux-gnu-
          - config: allyesconfig
            env:
              ARCH: riscv
              CROSS_COMPILE: riscv64-linux-gnu-

    env: ${{ matrix.env }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Git checkout Linux sources
      uses: actions/checkout@v2
      with:
        repository: krzk/linux.git
        ref: track/next
        path: sources

    - name: Install additional packages
      run: |
        ./bin/install.ubuntu.sh
        pip install dtschema yamllint

    - name: Make config
      run: make ${{ matrix.config }}
      working-directory: ./sources

    - name: Make dtbs_check
      run: make -j$(nproc) dtbs_check
      working-directory: ./sources
